--MENU
DermaPanel = vgui.Create( "DFrame" )
DermaPanel:SetPos( 50,50 )
DermaPanel:SetSize( 200, 350 )
DermaPanel:SetTitle( "Hax" )
DermaPanel:SetVisible( false )
DermaPanel:SetDraggable( true )
DermaPanel:ShowCloseButton( false )
DermaPanel:MakePopup()
 
local checkbox = vgui.Create( "DCheckBoxLabel", DermaPanel )
checkbox:SetConVar( "bhop_enabled" )
checkbox:SetText( "Enable Bhop?" )
checkbox:SetPos( 5, 25 )
checkbox:SizeToContents()

local checkbox = vgui.Create( "DCheckBoxLabel", DermaPanel )
checkbox:SetConVar( "tbot_enabled" )
checkbox:SetText( "Enable Trigger?" )
checkbox:SetPos( 5, 50 )
checkbox:SizeToContents()

local checkbox = vgui.Create( "DCheckBoxLabel", DermaPanel )
checkbox:SetConVar( "wall_enabled" )
checkbox:SetText( "Enable Wallhack?" )
checkbox:SetPos( 5, 75 )
checkbox:SizeToContents()

local checkbox = vgui.Create( "DCheckBoxLabel", DermaPanel )
checkbox:SetConVar( "npcwall_enabled" )
checkbox:SetText( "Enable NPC Wallhack?" )
checkbox:SetPos( 5, 100 )
checkbox:SizeToContents()

local checkbox = vgui.Create( "DCheckBoxLabel", DermaPanel )
checkbox:SetConVar( "pfaimbot_enabled" )
checkbox:SetText( "Enable Friendly Player Aimbot?" )
checkbox:SetPos( 5, 125 )
checkbox:SizeToContents()

local checkbox = vgui.Create( "DCheckBoxLabel", DermaPanel )
checkbox:SetConVar( "paimbot_enabled" )
checkbox:SetText( "Enable Player Aimbot?" )
checkbox:SetPos( 5, 150 )
checkbox:SizeToContents()

local checkbox = vgui.Create( "DCheckBoxLabel", DermaPanel )
checkbox:SetConVar( "pragebot_enabled" )
checkbox:SetText( "Enable Player Ragebot?" )
checkbox:SetPos( 5, 175 )
checkbox:SizeToContents()

local checkbox = vgui.Create( "DCheckBoxLabel", DermaPanel )
checkbox:SetConVar( "nfaimbot_enabled" )
checkbox:SetText( "Enable Friendly NPC Aimbot?" )
checkbox:SetPos( 5, 200 )
checkbox:SizeToContents()

local checkbox = vgui.Create( "DCheckBoxLabel", DermaPanel )
checkbox:SetConVar( "naimbot_enabled" )
checkbox:SetText( "Enable NPC Aimbot?" )
checkbox:SetPos( 5, 225 )
checkbox:SizeToContents()

local checkbox = vgui.Create( "DCheckBoxLabel", DermaPanel )
checkbox:SetConVar( "nragebot_enabled" )
checkbox:SetText( "Enable NPC Ragebot?" )
checkbox:SetPos( 5, 250 )
checkbox:SizeToContents()

local checkbox = vgui.Create( "DCheckBoxLabel", DermaPanel )
checkbox:SetConVar( "cross_enabled" )
checkbox:SetText( "Enable Custom Crosshair?" )
checkbox:SetPos( 5, 275 )
checkbox:SizeToContents()

--ESP MENU
ESPPanel = vgui.Create( "DFrame" )
ESPPanel:SetPos( 275,50 )
ESPPanel:SetSize( 200, 150 )
ESPPanel:SetTitle( "ESP" )
ESPPanel:SetVisible( false )
ESPPanel:SetDraggable( true )
ESPPanel:ShowCloseButton( false )
ESPPanel:MakePopup()

local checkbox = vgui.Create( "DCheckBoxLabel", ESPPanel )
checkbox:SetConVar( "espname_enabled" )
checkbox:SetText( "Enable Name?" )
checkbox:SetPos( 5, 25 )
checkbox:SizeToContents()

local checkbox = vgui.Create( "DCheckBoxLabel", ESPPanel )
checkbox:SetConVar( "esphealth_enabled" )
checkbox:SetText( "Enable Health?" )
checkbox:SetPos( 5, 50 )
checkbox:SizeToContents()

local checkbox = vgui.Create( "DCheckBoxLabel", ESPPanel )
checkbox:SetConVar( "espdistance_enabled" )
checkbox:SetText( "Enable Distance?" )
checkbox:SetPos( 5, 75 )
checkbox:SizeToContents()

local checkbox = vgui.Create( "DCheckBoxLabel", ESPPanel )
checkbox:SetConVar( "espbox_enabled" )
checkbox:SetText( "Enable Box?" )
checkbox:SetPos( 5, 100 )
checkbox:SizeToContents()

local checkbox = vgui.Create( "DCheckBoxLabel", ESPPanel )
checkbox:SetConVar( "espbone_enabled" )
checkbox:SetText( "Enable Bone?" )
checkbox:SetPos( 5, 125 )
checkbox:SizeToContents()